### ISSUE TITLE
can not pip install package

### ISSUE THREAD

**Issue by schosterbarak** [open-alchemy/json-source-map#2]
I am not sure why. got the following output:

 pip install json-source-map -i https://pypi.python.org/simple
Looking in indexes: https://pypi.python.org/simple
ERROR: Could not find a version that satisfies the requirement json-source-map (from versions: none)
ERROR: No matching distribution found for json-source-map

**Comment by WizardCM** [comment]
I get the same error. Looks like the package requires Python 3.9, and I'm running 3.8.

**Comment by jdkandersson** [comment]
Support for Python 3.8 has now been added, please let me know if you are still having issues.
